FROM node:20-bullseye

RUN npm install -g turbo

ARG APP=server

WORKDIR /app

COPY . .

RUN turbo prune front

RUN npm i
RUN cd packages/common && npx prisma@6.4.1 generate && cd ../..
RUN turbo build --filter=front

WORKDIR /app/front

EXPOSE 3000

CMD ["npm", "run", "start"]
