FROM node:20-alpine AS base

RUN npm install -g turbo

WORKDIR /app

COPY . .

RUN turbo prune server

WORKDIR /app/out

RUN npm i

RUN turbo run build --filter=server

WORKDIR /app/out/server

EXPOSE 3000

CMD ["npm", "run", "start"]
