FROM node:20-bullseye AS base

RUN npm install -g turbo

WORKDIR /app

COPY . .

RUN turbo prune front

WORKDIR /app/out

RUN npm i

RUN turbo run build --filter=front

WORKDIR /app/out/front

EXPOSE 3000

CMD ["npm", "run", "start"]
